[color-theme]
name = "Aleph"
color-preference = "dark"

[ui]
drop-shadow-width = 4

[color-theme.base]
white = "#ABB2BF"
black = "#282C34"
grey = "#3E4451"
light_grey = "#2c313c"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#e5c07b"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56b6c2"
magenta = "#C678DD"

[color-theme.ui]
"lapce.active_tab" = "#141417"
"lapce.inactive_tab" = "#101012"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#aaaaaa"
"lapce.scroll_bar" = "#aaaaaa40"

# Typically harser colors. Note that some colors are not actually their name's color
# but for the most part they are
"terminal.cursor" = "#ffb638"
"terminal.foreground" = "$orange"
"terminal.background" = "#141417"
"terminal.white" = "#eeeeee"
"terminal.black" = "#141417"
"terminal.red" = "#d62c2c"
"terminal.blue" = "#28a9ff"
"terminal.green" = "#42dd76"
"terminal.yellow" = "#ffb638"
"terminal.cyan" = "#14e5d4"
"terminal.magenta" = "#e66dff"
"terminal.bright_white" = "#28a9ff"
"terminal.bright_red" = "#d62c2c"
"terminal.bright_blue" = "#28a9ff"
"terminal.bright_green" = "#42dd76"
"terminal.bright_yellow" = "#ffb638"
"terminal.bright_cyan" = "#14e5d4"
"terminal.bright_magenta" = "#e66dff"
"terminal.bright_black" = "#28a9ff"

"editor.background" = "#141417"
"editor.foreground" = "#eeeeee"
"editor.dim" = "#20AA20"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#528bff"
"editor.selection" = "#aaaaaa25"
"editor.current_line" = "#aaaaaa0c"
"editor.link" = "$cyan"

"inlay_hint.foreground" = "#6E7177"

"source_control.added" = "#50a14f32"
"source_control.removed" = "#ff526632"
"source_control.modified" = "#0184bc32"

"palette.background" = "#21252B"
"palette.current" = "#2C313A"

"completion.background" = "#21252B"
"completion.current" = "#2C313A"

"hover.background" = "#21252B"

"activity.background" = "$black"
"activity.current" = "#21252B"

"panel.background" = "#141417"
"panel.current" = "#262626"
"panel.hovered" = "#4C4C4C"

"status.background" = "#21252B"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#898989"

[theme.syntax]
"comment" = "#5C6370"

"constant" = "#D62C2C"
"type" = "#A95EFF"
"typeAlias" = "#b079ee"
"number" = "$yellow"
"enum" = "#9263D3"
"enumMember" = "#AA63D3"
"struct" = "#A95EFF"
"structure" = "#A95EFF"
"attribute" = "$orange"
"constructor" = "$yellow"
"variable" = "#FF478D"
"macro" = "#28A9FF"
"operator" = "#EEEEEE60"
"variable.parameter" = "#FF478D"
"selfKeyword" = "#14E5D4"
"property" = "#FF7135"
"interface" = "#DD46C2"
"function" = "$blue"
"method" = "#28A9FF"
"function.method" = "$blue"
"keyword" = "#14E5D4"
"field" = "$red"
"enum-member" = "$red"
# "style.variable.other.member" = "$red"

"string" = "$green"

"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"
